### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by elministerr** [RotorHazard/RH_Install-Manager#26]
Hello there, 

I'm new to rotor hazard. I have a setup of Raspberry PI Zero 2W with Arduino and the receiver. 

However I have some problems to do an initial install.  I installed RaspbianOS lite 32 bit and used 

curl -sSL https://raw.githubusercontent.com/RotorHazard/Install-Manager/stable/scripts/auto_download.sh | bash

after the configuration tab I get followed error: 

Traceback (most recent call last):
  File "/home/rulehmann/RH_Install-Manager/start_rhim.py", line 33, in <module>
    main()
  File "/home/rulehmann/RH_Install-Manager/start_rhim.py", line 29, in main
    update.main()
  File "/home/rulehmann/RH_Install-Manager/update.py", line 573, in main
    main_menu(config)
  File "/home/rulehmann/RH_Install-Manager/update.py", line 494, in main_menu
    if not rhim_config.first_part_of_install and not rhim_config.second_part_of_install:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'first_part_of_install'

The output of my config is: ~/RH_Install-Manager/updater-config.json

{
  "user": "rotorhazard",
  "rh_version": "stable",
  "country": "DE",
  "nodes_number": 1,
  "gpio_reset_pin": false,
  "port_name": "ttyAMA0",
  "debug_mode": false,
  "debug_user": "default",
  "old_hw_mod": false,
  "pins_assignment": "default",
  "i2c_bus_number": 1,
  "beta_tester": false
}

any ideas ? 

I already reinstalled complete with the 64bit version but I get the same error.

**Comment by elministerr** [comment]
nvm resolved :) 

you have to put the exact username in the "user" field which you have chosen at the raspberry installation.

**Comment by szafranski** [comment]
Yes, but I will implement double check of this :) good it is resolved!
